# Database Configuration
spring:
  data:
    mongodb:
      database: transcendence

# Kafka Configuration
spring.cloud.stream.kafka:
  streams:
    default:
      consumer:
        startOffset: latest

# Channel configuration
spring.cloud.stream.bindings:
  # Topic
  zhihu-topic-request-channel:
    content-type: application/json
    destination: out-zhihu-topic-request
    group: zhihu-topic
  out-zhihu-topic-request:
    content-type: application/json
  in-zhihu-topic-callback-topic-page:
    content-type: application/octet-stream
    group: zhihu-topic
  in-zhihu-topic-callback-topic:
    content-type: application/octet-stream
    group: zhihu-topic
  in-zhihu-topic-callback-topic-list:
    content-type: application/octet-stream
    group: zhihu-topic
  in-zhihu-topic-callback-plazza-list:
    content-type: application/octet-stream
    group: zhihu-topic
  in-zhihu-topic-callback-feed-list:
    content-type: application/octet-stream
    group: zhihu-topic
  # Answer
  zhihu-answer-request-channel:
    content-type: application/json
    destination: out-zhihu-answer-request
    group: zhihu-answer
  out-zhihu-answer-request:
    content-type: application/json
  in-zhihu-answer-callback-answer:
    content-type: application/octet-stream
    group: zhihu-answer
  in-zhihu-answer-callback-member-answer:
    content-type: application/octet-stream
    group: zhihu-answer
  in-zhihu-answer-callback-question-answer:
    content-type: application/octet-stream
    group: zhihu-answer
  # Member
  zhihu-member-request-channel:
    content-type: application/json
    destination: out-zhihu-member-request
    group: zhihu-member
  out-zhihu-member-request:
    content-type: application/json
  in-zhihu-member-callback-member:
    content-type: application/octet-stream
    group: zhihu-member
  # Question
  zhihu-question-request-channel:
    content-type: application/json
    destination: out-zhihu-question-request
    group: zhihu-question
  out-zhihu-question-request:
    content-type: application/json
  in-zhihu-question-callback-question:
    content-type: application/octet-stream
    group: zhihu-question
  # Article
  zhihu-article-request-channel:
    content-type: application/json
    destination: out-zhihu-article-request
    group: zhihu-article
  out-zhihu-article-request:
    content-type: application/json
  in-zhihu-article-callback-article:
    content-type: application/octet-stream
    group: zhihu-article
  in-zhihu-article-callback-column-article:
    content-type: application/octet-stream
    group: zhihu-article
  # Column
  zhihu-column-request-channel:
    content-type: application/json
    destination: out-zhihu-column-request
    group: zhihu-column
  out-zhihu-column-request:
    content-type: application/json
  in-zhihu-column-callback-column:
    content-type: application/octet-stream
    group: zhihu-column
  # Comment
  zhihu-comment-request-channel:
    content-type: application/json
    destination: out-zhihu-comment-request
  out-zhihu-comment-request:
    content-type: application/json
  in-zhihu-comment-callback-answer-comment:
    in-zhihu-column-callback-column:
    content-type: application/octet-stream
    group: zhihu-comment
  in-zhihu-comment-callback-article-comment:
    in-zhihu-column-callback-column:
    content-type: application/octet-stream
    group: zhihu-comment
  in-zhihu-comment-callback-question-comment:
    in-zhihu-column-callback-column:
    content-type: application/octet-stream
    group: zhihu-comment

# Feign Client Configuration
feign.client.config.default:
  connectTimeout: 160000000
  readTimeout: 160000000

# Actuator Endpoints Configuration
management:
  endpoints:
    web:
      exposure:
        include: refresh
