server:
  port: 9100

zuul:
  ignored-services: '*'
  prefix: /api
  routes:
    zhihu-members-endpoints:
      path: /zhihu-members/**
      serviceId: zhihu-members
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
