server:
  port: 9100

zuul:
  ignored-services: '*'
  prefix: /api
  routes:
    zhihu-member-endpoints:
      path: /zhihu-member/**
      serviceId: zhihu_member
    zhihu-topic-endpoints:
      path: /zhihu-topic/**
      serviceId: zhihu-topic
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
