# Database Configuration
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      #username:
      #password:

# Kafka Configuration
spring.cloud.stream.kafka:
  binder:
    brokers: localhost
