server.port: 9800
# interval between the request in ms
transcendence.api.throttle.interval: 5000
spring:
  cloud:
    stream:
      bindings:
        input:
          destination: memberReqTopic
          content-type: application/json
      kafka:
        binder:
          brokers: localhost
